server:
  port: 8764
spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instance-id: consul-server-01
        service-name: consul-server-01
        port: ${server.port}
        health-check-url: http://${spring.cloud.consul.host}:${server.port}
        health-check-interval: 10s
        tags: dev











