server:
  port: 8888
spring:
  application:
    name: tesla-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EvanSole/tesla-spring-cloud-study
          search-paths: tesla-config
          username:
          password:
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/



